### PR TITLE
extracting zip files could be done in code itself

### PR DESCRIPTION
**Pull request by abhijithneilabraham**
The extraction of the zip file can take place inside the code and no need of manual extraction.This would also be helpful if this project is further made into a pip package.The extraction would not happen if the file is already there.

### CODE REVIEW

**Comment by abhijithneilabraham** [comment]
the piece of code
```
from app import app
```
should come after the zip file extraction to avoid -->filenotfounderror
So fixed that in the earlier commit

**Comment by minimalparts** [comment]
Great. Should we also check if the zip file itself is there? If someone clones the repo, they may forget to download the data in the first place.

**Comment by abhijithneilabraham** [comment]
I don't think the checking for zip file should be there, when I make a pip package, the zip file would also be there in the folder right? The extraction of zip file can be made on first time usage only, and thus, I am trying to reduce the size of pip package installation.

**Comment by minimalparts** [comment]
Okay. I was thinking of people still cloning things from GitHub rather than using the pip package. But sure, let's do it that way. I'll merge and we can always change things later if we want to. Thanks!

**Pull request merged**
