### PR TITLE
Upgrade to bootstrap 5, and related UI changes.

### PR DESCRIPTION
**Pull request by stultus**
This PR upgrades the bootstrap version to bootstrap 5.  
There are some admin listing pages pending to get the upgrade,  but it covers the rest.  

The design is not the best, but this is a start :)

### CODE REVIEW

**Comment by stultus** [comment]
Screenshot 2022-10-24 at 01-00-53 PeARS Search
Screenshot 2022-10-24 at 01-01-23 PeARS Search

**Comment by minimalparts** [comment]
Thanks @stultus! NIce! Just a tiny thing: on my screen, when I go to the indexer page, the second column is not horizontally aligned with the first one. But aside from this, all great. Just merge whenever you're ready.

**Comment by stultus** [comment]
@minimalparts Can you share a screenshot?

**Comment by minimalparts** [comment]
image

**Comment by minimalparts** [comment]
Ah, and in the DB admin, we now have two links to the URL list, rather than one to the pods :) Also, when I click on the see/modify URL button, the right hand-side of the table is cut. 

image

**Comment by stultus** [comment]
@minimalparts Can you check now?  It should be horizontally aligned (w.r.t the top line)

**Comment by stultus** [comment]
@minimalparts Ah, I haven't done anything in the DB admin edit pages(Since that page is from the flask-admin library),  It uses the old bootstrap itself.  I'll check it and submit it as a separate P.R.

**Comment by stultus** [comment]
My bad,  Will fix the links in this PR itself @minimalparts

**Comment by minimalparts** [comment]
Alignment is great now, thx!!

**Comment by stultus** [comment]
@minimalparts Can you check the DB admin now?   please force refresh to clear cache (shift + cntrl + r)

**Comment by minimalparts** [comment]
Yup! Pods are back :)

**Comment by stultus** [comment]
Looks like a good idea. 
I'll submit a separate PR for that. (Since it is not related to the bootatrap upgrade) 

Pod/url admin listing revamp also will be addressed in a separate PR

**Comment by minimalparts** [comment]
@stultus Great! Thank you! I'll let you merge in case you want to add anything else to this PR. For me, it's a go.

**Pull request merged**
